server:
  port: 8080
spring:
  application:
    name: my-rabbitmq
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 3000ms
