server:
  port: 8080

spring:
  application:
    name: my-rabbitmq
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    listener:
      type: simple
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 3000ms
